development:
  adapter: redis
  url: <%= ENV.fetch('REDIS_URL', 'redis://localhost:6379/0') %>
  channel_prefix: ny_2022_development
test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch('REDIS_URL', 'redis://localhost:6379/0') %>
  channel_prefix: ny_2022_production
